### PR TITLE
The Slow refactor and Publish addition

### LINKED ISSUE #10: [FR] Add Publish.css
This is for me, to be able to reference when I add the PR.

### PR DESCRIPTION
**Pull request by sigrunixia**
This PR will aim to do the following:
- [x] Proper Sassify the SCSS for best build practices with SASS
- [x] Add conformity to the dev docs
- [x] Add basic Publish support, with Publish specific fixes

Closes #10

### CODE REVIEW

**Comment by sigrunixia** [comment]
The first two commits do the following:
- [ ] Change foundation to foundations, as this is what the dev docs has. https://docs.obsidian.md/Reference/CSS+variables/Foundations/Borders
- [ ] Change @import to @use. If you use @import in multiple files, it adds the content over and over. Example, import in _foundations.scss, and again in theme.css, will make the items pulled duplicate needlessly. @use intelligently only keeps one copy, resulting in a smaller file.

**Comment by sigrunixia** [comment]
https://github.com/dbarenholz/halcyon-obsidian/pull/16/commits/dfa6dfdda40230e9eda02f763476071948f57e9c Will properly mark all relevant files as partials. It wasn't fun loading this up and having a bunch of unneeded CSS files show up. :rofl:

https://sass-lang.com/documentation/at-rules/import/#partials

**Comment by sigrunixia** [comment]
https://github.com/dbarenholz/halcyon-obsidian/pull/16/commits/407b523b271e2ea45f019c1cbb7fa35de6b7182f Adds Publish components. Please note the fix I submitted to dev docs. https://github.com/obsidianmd/obsidian-developer-docs/commit/bb41e883e41edd3540de6bd923cb813b8495473b

**Comment by sigrunixia** [comment]
https://github.com/dbarenholz/halcyon-obsidian/pull/16/commits/ca441e5909c8cd27d9da87c08577af7364f20448 Adds the missing variables, but commented out so they won't be built. I found many an ustyled instances that way.

**Comment by sigrunixia** [comment]
Based on this, I do not think we should try to add anything for RTL. We don't have a good way to test for anything breaking. https://docs.obsidian.md/Plugins/User+interface/Right-to-left#Obsidian+CSS+helpers+and+rules+for+RTL

**Comment by sigrunixia** [comment]
https://github.com/dbarenholz/halcyon-obsidian/pull/16/commits/baa5c5ce7a5976d2b5b5f8ca768c21931ad51152 Adds the base items needed to make Publish work and look like Halcyon.

**Comment by sigrunixia** [comment]
https://github.com/dbarenholz/halcyon-obsidian/pull/16/commits/16f7a439026a9685691442a4c63d3dad2c02f552 Turns out dev docs forgot to make some changes

**Review by dbarenholz — APPROVED** [review]
This is absolutely magnificent. Thank you for all the effort :pray:

**Pull request merged**
